# Generated by Django 4.0.5 on 2022-07-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='customer_pk',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
